### ISSUE TITLE
Request size exceeded

### ISSUE THREAD

**Issue by Nuru** [uken/fluent-plugin-elasticsearch#588]
#### Problem
Despite #586, push to Elasticsearch fails due to Request size exceeded, even when `bulk_message_request_threshold` is set. This is an issue because AWS Elasticsearch has a hard limit on request size of 10 MB. As far as I can tell, https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/30 describes this exact same issue, which was [implied could be fixed](https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/30) by making #539 configurable, which is what #586 did.

#535 explains an identical issue except with a bigger hard limit coming from a proxy, which is why it is good that this is configurable, but in all 3 cases we need a way to set a hard limit the size of the generated requests.

#### Steps to replicate

Using AWS Elasticsearch, send a backlog of logs quickly. Config:
```
  <match **>
    @type elasticsearch
    @id out_es
    @log_level "info"
    include_tag_key true
    host "elasticsearch-REDACTED.eu-west-2.es.amazonaws.com"
    port 443
    path ""
    scheme https
    ssl_verify true
    ssl_version TLSv1_2
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    logstash_prefix "logstash"
    logstash_format true
    index_name "logstash"
    type_name "fluentd"
    bulk_message_request_threshold 10M
    <buffer>
      flush_thread_count 8
      flush_interval 2s
      chunk_limit_size 8M
      queue_limit_length 64
      retry_max_interval 30
      retry_forever true
    </buffer>
  </match>
```

Example message (edited for brevity)
```
Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster..."
Message: Request size exceeded 10485760 bytes
location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.5.1/lib/fluent/plugin/out_elasticsearch.rb:758:in `rescue in send_bulk'"
```

#### Expected Behavior or What you need to ask

Expected Request size not to exceed `bulk_message_request_threshold` and therefore not to get this error. 

#### Using Fluentd and ES plugin versions

* OS version: From Docker image  `fluent/fluentd:v1.4.2-debian-2.0`
* Bare Metal or within Docker or Kubernetes or others?  Kubernetes 1.12.8
* Fluentd v0.12 or v0.14/v1.0
  * 1.4.2
* ES plugin 3.x.y/2.x.y or 1.x.y
  * ES plugin 3.5.1
  * [Link to Gemfile.lock](https://github.com/cloudposse/fluentd-kubernetes-daemonset/blob/fe732f9/docker-image/v1.4/debian-elasticsearch/Gemfile.lock)

* ES version (optional): AWS ES 6.5

**Comment by cosmo0920** [comment]
> Despite #586, push to Elasticsearch fails due to Request size exceeded, even when `bulk_message_request_threshold` is set

This is because it is not *limit* but **threshold**.
It does not fire to accurate splitting events.
It works just threshold for bulk operation.

This works as:

* chunk 11MB arrived then split events _but not to 10MB and 1MB_.

**Comment by Nuru** [comment]
> This is because it is not _limit_ but **threshold**.

I do not understand the benefit of this feature if it is not a _limit_.  #586 referenced #584, making the threshold configurable apparently to make it possible to disable the feature, because the feature was using too much CPU. 

However, as acknowledged in https://github.com/uken/fluent-plugin-elasticsearch/issues/584#issuecomment-491120535, the feature being modified was introduced in #539 which closed #535. https://github.com/uken/fluent-plugin-elasticsearch/issues/535#issuecomment-460158637 says #539 "limits bulk_message contents length", which is what is needed to fix #535, which complains about the error "Request Content-Length 528883194 exceeds the configured limit of 209715200".

In both this case and #535, the underlying issue to be addressed is that the server has a hard limit on the request size and we need `fluentd` to ensure that it does not send requests that are too big and therefore doomed to fail forever. So if #539 does not implement such a feature, please update the feature so that it does implement a limit.

**Comment by Nuru** [comment]
I updated the problem statement with more details on the nature of the problem and requirements for a solution.

**Comment by cosmo0920** [comment]
Please write a patch to fulfill your requirement. Thanks!!

**Comment by cosmo0920** [comment]
I'm reconsidering issue.
The conclusion is: it is impossible to fix this issue precisely.
Because Fluentd does not have rate limit feature (inbound/outbound).

For now, you should set `bulk_message_request_threshold 9MB`.

The other logging platform also have an output plugin which is logstash-output-elasticsearch.
It also handles as threshold not precise request size limitation:
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/4312df7d671e5ea7cb8224d12c38e0223c14051c/lib/logstash/outputs/elasticsearch/http_client.rb#L122

**Comment by Nuru** [comment]
I am not sure what you mean by "precisely". The requirement is to ensure that messages to Elasticsearch do not exceed a certain size, not that they get as close as possible to that size. The [logstash plugins](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/4312df7d671e5ea7cb8224d12c38e0223c14051c/lib/logstash/outputs/elasticsearch/http_client.rb#L122) that you refer to do both. They see if the current buffer plus the new message would cause the buffer to exceed the maximum message size, and if it would, they send and clear the buffer before adding the new message to it. 

Unless a single message is larger than the request size limit, in which chase you would have no choice but to either truncate or discard that message, the above algorithm is as precise a fix as is practical. 

Setting `bulk_message_request_threshold 9MB` is not sufficient. You don't know what size buffer chunk is coming or [how big that chunk will be when expanded to JSON](https://docs.fluentd.org/buffer#buffers-chunk-size-and-outputs-payload-size-are-sometimes-different-why). If the chunk expands to bigger than 1 MB, then you could still exceed the 10 MB limit.

**Comment by cosmo0920** [comment]
> Setting `bulk_message_request_threshold 9MB` is not sufficient. You don't know what size buffer chunk is coming or [how big that chunk will be when expanded to JSON](https://docs.fluentd.org/buffer#buffers-chunk-size-and-outputs-payload-size-are-sometimes-different-why). If the chunk expands to bigger than 1 MB, then you could still exceed the 10 MB limit.

Really? Yeah, I know it is not sufficient to set up buffer related parameters to adjust request size.
But, in ES plugin `#write`, chunk is already expanded and x-ndjson encoded:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L593-L630
 https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L503-L526
Is these lines implementation not enough for you?

**Comment by Nuru** [comment]
@cosmo0920 
> Really? Yeah, I know it is not sufficient to set up buffer related parameters to adjust request size.
> But, in ES plugin `#write`, chunk is already expanded and x-ndjson encoded:
> https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L593-L630
> https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L503-L526
> Is these lines implementation not enough for you?

I opened this bug because I had actual problems in production with the code you cited above, not because I looked at the code and thought it was not good. I reduced `bulk_message_request_threshold` to `8M` and still had failures in production. 

The solution is to do what they did in [logstash plugins](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/4312df7d671e5ea7cb8224d12c38e0223c14051c/lib/logstash/outputs/elasticsearch/http_client.rb#L122). Simply ensure that you send the buffer before allowing it to grow beyond the size limit.

**Comment by cosmo0920** [comment]
Hmm..., you mean that we should check bulk_message size before appending another bulk_message like this?

```diff
 diff --git a/lib/fluent/plugin/out_elasticsearch.rb b/lib/fluent/plugin/out_elasticsearch.rb
index 1ead4fc..a943ad6 100644
--- a/lib/fluent/plugin/out_elasticsearch.rb
+++ b/lib/fluent/plugin/out_elasticsearch.rb
@@ -600,17 +600,18 @@ EOC
                    RequestInfo.new(host, nil)
                  end

+          if split_request?(bulk_message, info)
+            bulk_message.each do |info, msgs|
+              send_bulk(msgs, tag, chunk, bulk_message_count[info], extracted_values, info) unless msgs.empty?
+              msgs.clear
+              # Clear bulk_message_count for this info.
+              bulk_message_count[info] = 0;
+              next
+            end
+          end
+
           if append_record_to_messages(@write_operation, meta, header, record, bulk_message[info])
             bulk_message_count[info] += 1;
-            if split_request?(bulk_message, info)
-              bulk_message.each do |info, msgs|
-                send_bulk(msgs, tag, chunk, bulk_message_count[info], extracted_values, info) unless msgs.empty?
-                msgs.clear
-                # Clear bulk_message_count for this info.
-                bulk_message_count[info] = 0;
-                next
-              end
-            end
           else
             if @emit_error_for_missing_id
               raise MissingIdFieldError, "Missing '_id' field. Write operation is #{@write_operation}"
```

**Comment by Nuru** [comment]
@cosmo0920 

> Hmm..., you mean that we should check bulk_message size before appending another bulk_message like this?

No, I think cosmo0920@9227eca172a07207117f3e2aded6a3713e3b0609 does not work because you are still waiting until after the bulk message is too big before sending it. (I'm not sure if I'm following your code correctly, which is why I have not submitted a PR.)

**Comment by ionosphere80** [comment]
None of these fixes appear to solve the problem. Any updates on an actual resolution?

**Comment by Nuru** [comment]
@ionosphere80 until we get a real fix, I believe the workaround is to ensure that `bulk_message_request_threshold + chunk_limit_size + 16k <= actual_message_size_limit`. The 16k is meant to cover other overhead like headers, may not be needed, or may need to be bigger.

**Comment by ionosphere80** [comment]
Hi @Nuru,

I'm getting this error after trying your suggestion:

```[warn]: parameter 'chunk_size_limit' in <buffer tag, time>
  @type "file"
  path "/tmp/buffer/es-all"
  timekey 60
  chunk_size_limit 2MB
  flush_mode interval
  flush_thread_count 2
</buffer> is not used.```

**Comment by Nuru** [comment]
@ionosphere80 The parameter to set is `chunk_limit_size` not `chunk_size_limit`

**Comment by ionosphere80** [comment]
Doh, my bad... long day already.

**Comment by cosmo0920** [comment]
> bulk_message_request_threshold + chunk_limit_size + 16k <= actual_message_size_limit

Fluentd core does not have controlling flow rate.

@Nuru 's solution is the better idea to limit sending maximum body size.

**Comment by fernandosure** [comment]
@Nuru what is your recommendation for each of these values `bulk_message_request_threshold + chunk_limit_size + 16k <= actual_message_size_limit`
