### ISSUE TITLE
The latest version breaks with usage of @type elasticsearch_dynamic

### ISSUE THREAD

**Issue by pragmaticivan** [uken/fluent-plugin-elasticsearch#193]
#### Problem

I'm testing the latest release with fluentd 0.14, if I use @type elasticsearch_dynamic even If I don't use any dynamic value it still breaks.
#### Steps to replicate

```
<source>
  type forward
  port 24224
  bind 0.0.0.0
</source>

<filter docker.apache.*>
  @type record_transformer

  enable_ruby true
  renew_record true
  keep_keys source

  <record>
    containerUid ${record['container_id']}
    recorded_json ${record.to_json}
    level 3
  </record>
</filter>

<match docker.apache.*>
  @type elasticsearch_dynamic
  host elasticsearch
  port 9200

  logstash_format true
  logstash_prefix "fluentd-docker1t"
  time_key_exclude_timestamp true

  buffer_type memory
  buffer_chunk_limit 1m
  buffer_queue_limit 128
  flush_interval 1s
  retry_wait 1s
  max_retry_wait 10s
</match>
```

Error: 

```
fluentd          | 2016-08-24 18:50:02 +0000 [info]: listening fluent socket on 0.0.0.0:24224
fluentd          | 2016-08-24 18:50:09 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=0 next_retry=2016-08-24 18:50:10 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/excon-0.52.0/lib/excon/connection.rb:228:in `request'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/excon.rb:55:in `call'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:257:in `call'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/ping.rb:20:in `ping'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.6.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:61:in `client'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.6.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:190:in `rescue in send'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.6.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:188:in `send'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.6.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:181:in `block in write'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.6.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:180:in `each'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.6.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:180:in `write'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.2/lib/fluent/compat/output.rb:125:in `write'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.2/lib/fluent/plugin/output.rb:802:in `try_flush'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.2/lib/fluent/plugin/output.rb:979:in `flush_thread_run'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.2/lib/fluent/plugin/output.rb:369:in `block (2 levels) in start'
fluentd          |   2016-08-24 18:50:09 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.2/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
fluentd          | 2016-08-24 18:50:10 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=1 next_retry=2016-08-24 18:50:11 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:10 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:50:11 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=2 next_retry=2016-08-24 18:50:13 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:11 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:50:13 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=3 next_retry=2016-08-24 18:50:17 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:13 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:50:17 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=4 next_retry=2016-08-24 18:50:24 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:17 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:50:24 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=5 next_retry=2016-08-24 18:50:34 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:24 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:50:34 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=6 next_retry=2016-08-24 18:50:44 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:34 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:50:44 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=7 next_retry=2016-08-24 18:50:55 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:44 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:50:55 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=8 next_retry=2016-08-24 18:51:04 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:50:55 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:51:04 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=9 next_retry=2016-08-24 18:51:14 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:51:04 +0000 [warn]: suppressed same stacktrace
fluentd          | 2016-08-24 18:51:14 +0000 [warn]: failed to flush the buffer. plugin_id="object:2aac5010251c" retry_time=10 next_retry=2016-08-24 18:51:25 +0000 chunk="53ad5c0187743d67a775301e39b5c61b" error_class=NoMethodError error="undefined method `+' for nil:NilClass"
fluentd          |   2016-08-24 18:51:14 +0000 [warn]: suppressed same stacktrace
```

**Comment by pitr** [comment]
hmm, so according to stacktrace, [the host is nil](https://github.com/excon/excon/blob/v0.52.0/lib/excon/connection.rb#L228)

did it used to work with fluentd v0.12?

**Comment by pragmaticivan** [comment]
Yes @pitr it used to work on v0.12, I just upgraded, and removing dynamic to use the normal version works fine.

**Comment by pitr** [comment]
This is definitely a bug. Config I used to replicate it is:

```
<match to.es>
  @type elasticsearch_dynamic
  logstash_format true
  host localhost
  port 9200
  flush_interval 2s
</match>

<source>
  @type dummy
  tag to.es
  dummy {"hello":"world","@timestamp":"Thu Nov 29 14:33:20 GMT 2001"}
  rate 1
</source>
```

**Comment by edouardKaiser** [comment]
We are facing the same issue

**Comment by pitr** [comment]
PRs are welcomed.

Also, please try to reproduce using branch from #202

**Comment by therc** [comment]
I don't know Ruby, but could this be related to https://github.com/uken/fluent-plugin-elasticsearch/pull/206/files?

**Comment by therc** [comment]
This is still happening, even with 1.9.1. :-(

**Comment by repeatedly** [comment]
I wrote a patch for this problem.
Please test > https://github.com/uken/fluent-plugin-elasticsearch/pull/224

**Comment by therc** [comment]
the PR worked for me... thank you so much! looking forward to this change.

**Comment by pitr** [comment]
fixed with #224
